export const questionBank = [
  "What is your favorite memory of us from this year?",
  "When did you feel most loved by me recently?",
  "What is a tiny moment with me you want to keep forever?",
  "How have we grown together this year?",
  "What challenge did we face that made us stronger?",
  "What is one habit of mine you have come to appreciate?",
  "What is a place you want to revisit with me?",
  "What is a new tradition you want us to start?",
  "What is a song that feels like us right now?",
  "When did you feel proud of us?",
  "What is one way I surprised you this year?",
  "What is your favorite way we spend slow mornings?",
  "What makes our love feel safe?",
  "What is one thing you want to learn together?",
  "What moment made you laugh the hardest with me?",
  "What is a small gesture of mine that means a lot to you?",
  "What do you admire most about how we handle hard days?",
  "What is a future adventure you want us to plan?",
  "What does home feel like with me?",
  "What is your favorite photo of us this year and why?",
  "What is a scent, flavor, or sound that reminds you of us?",
  "What do you love about our everyday routines?",
  "What is one thing you want us to protect in our relationship?",
  "What is a goal you want to reach together next year?",
  "What is a compliment you never get tired of hearing?",
  "When did you feel most supported by me?",
  "What is your favorite date we had this year?",
  "What is a new thing you discovered about me this year?",
  "What does romance look like in our life right now?",
  "What is a trip you want us to take and why?",
  "What is a moment you felt especially grateful for us?",
  "What is a love lesson this year taught you?",
  "What is one way I make your life easier?",
  "What is a comfort ritual we share?",
  "What is a memory you want to recreate?",
  "What is one way you want to show me love more often?",
  "What do you think is our secret superpower as a couple?",
  "What is a surprise you would love to plan for me?",
  "What is your favorite thing we cooked together?",
  "What is a book, movie, or show that feels like us?",
  "What is a time I took care of you that you still think about?",
  "What is a moment you felt seen by me?",
  "What is one way we handled conflict well?",
  "What is something you are proud of me for?",
  "What is a dream you want to cheer me on toward?",
  "What is a simple joy we share?",
  "What is a new place in our city you want to explore together?",
  "What do you love about the way we communicate?",
  "What is a memory of us that always makes you smile?",
  "What is a question you hope I ask you more often?",
  "What is your favorite shared meal this year?",
  "What is a time you felt most connected to me?",
  "What is a small detail about me you adore?",
  "What is a tradition from our past you want to keep?",
  "What is your favorite way to spend a rainy day with me?",
  "What is a dream home detail you want us to have someday?",
  "What is one way we can make next year more playful?",
  "What is a story you love telling about us?",
  "What is a habit we should build as a team?",
  "What is a boundary that keeps our love healthy?",
  "What is a song lyric that captures our love lately?",
  "What does trust look like for us right now?",
  "What is a compliment you want to give me today?",
  "What do you love about our quiet moments?",
  "What is your favorite holiday memory with me?",
  "What is a surprise of mine that still makes you blush?",
  "What is one thing you want to forgive or release this year?",
  "What is a way I make you feel brave?",
  "What is a dream date you want to plan?",
  "What is a promise you want us to make for next year?",
  "What is a moment we felt like a perfect team?",
  "What is a skill you want us to learn together?",
  "What is your favorite place to hold my hand?",
  "What is a moment that made you realize how far we have come?",
  "What is one way we can deepen our intimacy?",
  "What do you love about our texts or notes to each other?",
  "What is a gift you loved giving or receiving from me?",
  "What is a milestone you want to celebrate together?",
  "What is something you want to remember about this season of life?",
  "What is a color or palette that feels like us?",
  "What is your favorite way to be comforted by me?",
  "What is a time I helped you feel confident?",
  "What is a memory of us at night you adore?",
  "What is a moment you felt we were perfectly in sync?",
  "What is a dream you want us to support for each other?",
  "What is your favorite way we say goodbye or hello?",
  "What is one way we can create more rest together?",
  "What is a family or friend moment with me you cherish?",
  "What is your favorite shared playlist or song right now?",
  "What is a photo you want us to take this year?",
  "What is a new restaurant or coffee spot you want to try with me?",
  "What is a ritual you want us to keep on Valentine's Day?",
  "What makes our love feel adventurous?",
  "What is a way I make ordinary days feel special?",
  "What is a boundary you appreciate me respecting?",
  "What is a way you want to celebrate us this year?",
  "What do you want more of in our relationship?",
  "What is something you never want to stop doing together?",
  "What is one word that describes our love right now?",
  "What is one thing you would tell future us about this year?",
  "What is a moment you felt deeply grateful for our partnership?",
  "What is a time we turned a bad day into a good one?",
  "What is a flavor, drink, or dessert that reminds you of us?",
  "What is one thing you want me to remember about you?",
  "What is a place you want to watch the sunset with me?",
  "What is your favorite cuddle or hug memory this year?",
  "What is a plan you want us to make for next February?",
  "What is a way we can be kinder to each other this year?",
  "What is a small tradition we should start this month?",
  "What is a time you felt I truly understood you?",
  "What is your favorite thing we built together?",
  "What is a word you associate with our love story?",
  "What is a way we can celebrate each other's wins more?",
  "What is something about me that inspires you?",
  "What is one thing you want to explore about our relationship?",
  "What is a time we supported each other's dreams?",
  "What is a moment of kindness from me you still feel?",
  "What does forever mean to you with me?",
  "What is your favorite way we end the day together?",
  "What is a dream trip we should put on our list?",
  "What is a tiny detail of our home you love?",
  "What is a moment you felt utterly lucky to love me?",
  "What is one change this year that strengthened us?",
  "What is a love note you want to leave me?",
  "What is one thing you hope we are still doing in five years?",
  "What is a time we showed up for each other beautifully?",
  "What is a memory of us that you wish had lasted longer?",
  "What is a ritual that helps you feel close to me?",
  "What is a place that feels like ours?",
  "What do you want to remember about our laughter this year?",
  "What is a way we can keep romance effortless?",
  "What is a habit you want to build just for us?",
  "What is a moment you felt cozy and content with me?",
  "What is a time we were brave together?",
  "What is a dream you want to share with me tonight?"
];
